#!/usr/bin/expect -f
#!/usr/bin/bash
spawn ssh-keygen
expect "Enter file in which to save the key (/root/.ssh/id_rsa):" {send "\n"}
expect "Enter passphrase (empty for no passphrase):" {send "\n"}
expect "Enter same passphrase again:" {send "\n"}
expect eof
